<?php
declare(strict_types=1);

/**
 * Core Header (AUTO-SEO ENABLED)
 * Owns ALL page structure opening.
 * 
 * Automatically renders SEO tags generated by themes.php + seo.php
 * No manual configuration needed - everything is auto-discovered.
 */

$siteName = trim((string) (class_exists('themes') ? themes::get('site_name') : ''));
if ($siteName === '') {
    $siteName = 'Chaos CMS';
}

$title = trim((string) (class_exists('themes') ? themes::get('title') : ''));
if ($title === '') {
    $title = $siteName;
}

$bodyClass = trim((string) (class_exists('themes') ? themes::get('body_class') : ''));

$meta = class_exists('themes') ? themes::get('meta') : [];
if (!is_array($meta)) {
    $meta = [];
}
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= htmlspecialchars($title, ENT_QUOTES, 'UTF-8'); ?></title>

<?php
// Standard meta tags (auto-generated from DB/filesystem)
foreach ($meta as $name => $content):
    if ($name !== '' && $content !== ''):
?>
    <meta name="<?= htmlspecialchars($name, ENT_QUOTES, 'UTF-8'); ?>" content="<?= htmlspecialchars($content, ENT_QUOTES, 'UTF-8'); ?>">
<?php
    endif;
endforeach;
?>

<?php
// Canonical URL (auto-generated)
if (class_exists('themes')) {
    echo themes::get_canonical();
}
?>

<?php
// Open Graph tags (auto-generated from DB/filesystem)
if (class_exists('themes')) {
    echo themes::get_opengraph();
}
?>

<?php
// Twitter Card tags (auto-generated from DB/filesystem)
if (class_exists('themes')) {
    echo themes::get_twitter_card();
}
?>

<?= class_exists('themes') ? themes::favicon_links() : ''; ?>
<?= class_exists('themes') ? themes::css_links() : ''; ?>

<?php
// JSON-LD Structured Data (auto-generated)
if (class_exists('themes')) {
    echo themes::get_schema();
}
?>
</head>

<body<?= $bodyClass !== '' ? ' class="' . htmlspecialchars($bodyClass, ENT_QUOTES, 'UTF-8') . '"' : ''; ?>>
<div class="site-wrap">

<header class="site-header">
<?php
// Nav is CONTENT ONLY
if (class_exists('themes')) {
    themes::render_nav();
}
?>
</header>

<main class="site-main">
